#!/usr/bin/env python3
"""Generate docs/tools.md from the canonical tool registry.

Run `make docs` (or `python scripts/generate_tools_doc.py`) after changing
`tools/registry.py`. The output is derived entirely from `list_tools()` -
the same data MCP clients see via `tools/list` - plus the open-world/
destructive annotation set `server.py` computes tool annotations from, so
this doc cannot drift out of sync with either. Never hand-edit
`docs/tools.md`; it will be silently overwritten on the next run.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from deep_agentic_core_mcp.server import _OPEN_WORLD_TOOLS
from deep_agentic_core_mcp.tools.registry import list_tools

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "tools.md"

# Known categories get a friendly heading and a fixed order; anything else
# (a category added to registry.py without updating this map) still renders,
# alphabetically, at the end - so a new category can't silently vanish from
# the doc, it just looks less polished until this map is updated too.
_CATEGORY_ORDER = ["core", "lens", "chaos", "spec"]
_CATEGORY_TITLES = {
    "core": "Core",
    "lens": "AgenticLens (`lens.*`)",
    "chaos": "Agentic Chaos (`chaos.*`)",
    "spec": "AI Operations Specification (`spec.*`)",
}


def _render_tool(tool: dict[str, Any]) -> str:
    lines = [f"### `{tool['name']}` — {tool['title']}", "", tool["description"], ""]
    lines.append("| | |")
    lines.append("| --- | --- |")
    lines.append(f"| Category | `{tool['category']}` |")
    prereqs = ", ".join(f"`{p}`" for p in tool["prerequisites"]) or "none"
    lines.append(f"| Prerequisites | {prereqs} |")
    lines.append(f"| Expected duration | {tool['expected_duration']} |")
    lines.append(f"| Mutates session | {'yes' if tool['mutates_session'] else 'no'} |")
    if tool["name"] in _OPEN_WORLD_TOOLS:
        lines.append("| Executes external code | **yes** — see [SECURITY.md](../SECURITY.md) |")
    lines.append("")
    lines.append("Input schema:")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(tool["input_schema"], indent=2))
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def generate() -> str:
    tools = list_tools()
    by_category: dict[str, list[dict[str, Any]]] = {}
    for tool in tools:
        by_category.setdefault(tool["category"], []).append(tool)

    lines = [
        "<!-- AUTO-GENERATED by scripts/generate_tools_doc.py - do not hand-edit. -->",
        "<!-- Run `make docs` (or `python scripts/generate_tools_doc.py`) to regenerate. -->",
        "",
        "# Tool Reference",
        "",
        f"{len(tools)} tools, generated from `tools/registry.py` - the same data MCP",
        "clients see via `tools/list`. See [README.md](../README.md) for a one-line-per-tool",
        "overview and [ROADMAP.md](../ROADMAP.md) for what's shipped per phase.",
        "",
    ]
    for category in _CATEGORY_ORDER:
        category_tools = by_category.pop(category, [])
        if not category_tools:
            continue
        lines.append(f"## {_CATEGORY_TITLES.get(category, category)}")
        lines.append("")
        for tool in sorted(category_tools, key=lambda t: str(t["name"])):
            lines.append(_render_tool(tool))
    for category, category_tools in sorted(by_category.items()):
        lines.append(f"## {category}")
        lines.append("")
        for tool in sorted(category_tools, key=lambda t: str(t["name"])):
            lines.append(_render_tool(tool))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(generate(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
